// Generated by `npm run vercel:build` before Vercel packages the function.
// @ts-expect-error The bundled file is created during the Vercel build step.
export { default } from "./dist/vercel/server.mjs";
